# Site settings
title: James Kerr | Software Engineer
description: "A Ruby on Rails developer in San Francisco, CA"
email: jkerr838@gmail.com
url: "http://jameskerr.info" # the base hostname & protocol for your site
twitter_username: jkerr838
github_username:  jameskerr
my_face: james_andrew_kerr_3.jpg

nav:
  - Home:    /
  - Work:    /work
  - About:   /about
  - Blog:    /blog
  - Contact: /contact

exclude:
  - Gemfile
  - Gemfile.lock
  - Guardfile
  - Procfile
  - Rakefile

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

# Asset settings
assets:
  cachebust: hard
