# Site settings
title: James Kerr | Website Developer/Software Engineer
description: "I creates websites, apps, and software with an intense focus on blending great design with powerful application."  
email: jkerr838@gmail.com
url: "http://jameskerr.info" # the base hostname & protocol for your site
twitter_username: jkerr838
github_username:  jameskerr

nav:
  - Home:    /
  - Work:    /work
  - About:   /about
  - Blog:    /blog
  - Contact: /contact

exclude:
  - Gemfile
  - Gemfile.lock
  - Guardfile
  - Procfile
  - Rakefile

# Build settings
markdown: redcarpet
redcarpet: 
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

# Asset settings
assets:
  js_compressor: yui
  css_compressor: yui
  cachebust: hard